SELECT * FROM ROAD_ACCIDENT_DATA;
-- find current year total number of casualties and compare increase or decrease percentage CY vs PY
SELECT TOTAL_CY_CASUALTIES, CY_VS_PY_PCT
FROM (SELECT ROUND(CAST(SUM(NUMBER_OF_CASUALTIES) AS NUMERIC)/1000, 2) || ' K' AS TOTAL_CY_CASUALTIES
FROM ROAD_ACCIDENT_DATA
WHERE YEAR = (SELECT MAX(YEAR) FROM ROAD_ACCIDENT_DATA)) AS X
CROSS JOIN (SELECT ROUND((CAST(SUM(NUMBER_OF_CASUALTIES)-(SELECT SUM(NUMBER_OF_CASUALTIES)
								  FROM ROAD_ACCIDENT_DATA
								  WHERE YEAR = (SELECT MAX(YEAR) FROM ROAD_ACCIDENT_DATA)-1) AS NUMERIC)/
								  (SELECT SUM(NUMBER_OF_CASUALTIES)
								  FROM ROAD_ACCIDENT_DATA
								  WHERE YEAR = (SELECT MAX(YEAR) FROM ROAD_ACCIDENT_DATA)-1))*100, 2) || ' %' AS CY_VS_PY_PCT
FROM ROAD_ACCIDENT_DATA
WHERE YEAR = (SELECT MAX(YEAR) FROM ROAD_ACCIDENT_DATA)) AS Y;

-- find current year total number of accidents and compare increase or decrease percentage CY vs PY
SELECT TOTAL_CY_ACCIDENTS, CY_VS_PY_PCT
FROM (SELECT ROUND(CAST(COUNT(ACCIDENT_INDEX) AS NUMERIC)/1000, 2) || ' K' AS TOTAL_CY_ACCIDENTS
FROM ROAD_ACCIDENT_DATA
WHERE YEAR = (SELECT MAX(YEAR) FROM ROAD_ACCIDENT_DATA)) AS X
CROSS JOIN (SELECT ROUND((CAST(COUNT(ACCIDENT_INDEX)-(SELECT COUNT(ACCIDENT_INDEX)
								  FROM ROAD_ACCIDENT_DATA
								  WHERE YEAR = (SELECT MAX(YEAR) FROM ROAD_ACCIDENT_DATA)-1) AS NUMERIC)/
								  (SELECT COUNT(ACCIDENT_INDEX)
								  FROM ROAD_ACCIDENT_DATA
								  WHERE YEAR = (SELECT MAX(YEAR) FROM ROAD_ACCIDENT_DATA)-1))*100, 2) || ' %' AS CY_VS_PY_PCT
FROM ROAD_ACCIDENT_DATA
WHERE YEAR = (SELECT MAX(YEAR) FROM ROAD_ACCIDENT_DATA)) AS Y;

-- find current year total number of casualties for fatal and compare increase or decrease percentage CY vs PY
SELECT TOTAL_FATAL_CASUALTIES, CY_VS_PY_PCT
FROM (SELECT ROUND(CAST(SUM(NUMBER_OF_CASUALTIES) AS NUMERIC)/1000, 2) || ' K' AS TOTAL_FATAL_CASUALTIES
FROM ROAD_ACCIDENT_DATA
WHERE YEAR = (SELECT MAX(YEAR) FROM ROAD_ACCIDENT_DATA) AND ACCIDENT_SEVERITY = 'Fatal') AS X
CROSS JOIN (SELECT ROUND((CAST(SUM(NUMBER_OF_CASUALTIES)-(SELECT SUM(NUMBER_OF_CASUALTIES)
								  FROM ROAD_ACCIDENT_DATA
								  WHERE ACCIDENT_SEVERITY = 'Fatal' AND YEAR = (SELECT MAX(YEAR) FROM ROAD_ACCIDENT_DATA)-1) AS NUMERIC)/
								  (SELECT SUM(NUMBER_OF_CASUALTIES)
								  FROM ROAD_ACCIDENT_DATA
								  WHERE ACCIDENT_SEVERITY = 'Fatal' AND YEAR = (SELECT MAX(YEAR) FROM ROAD_ACCIDENT_DATA)-1))*100, 2) || ' %' AS CY_VS_PY_PCT
FROM ROAD_ACCIDENT_DATA
WHERE YEAR = (SELECT MAX(YEAR) FROM ROAD_ACCIDENT_DATA) AND ACCIDENT_SEVERITY = 'Fatal') AS Y;

-- find current year total number of casualties for fatal and compare increase or decrease percentage CY vs PY
SELECT TOTAL_SERIOUS_CASUALTIES, CY_VS_PY_PCT
FROM (SELECT ROUND(CAST(SUM(NUMBER_OF_CASUALTIES) AS NUMERIC)/1000, 2) || ' K' AS TOTAL_SERIOUS_CASUALTIES
FROM ROAD_ACCIDENT_DATA
WHERE YEAR = (SELECT MAX(YEAR) FROM ROAD_ACCIDENT_DATA) AND ACCIDENT_SEVERITY = 'Serious') AS X
CROSS JOIN (SELECT ROUND((CAST(SUM(NUMBER_OF_CASUALTIES)-(SELECT SUM(NUMBER_OF_CASUALTIES)
								  FROM ROAD_ACCIDENT_DATA
								  WHERE ACCIDENT_SEVERITY = 'Serious' AND YEAR = (SELECT MAX(YEAR) FROM ROAD_ACCIDENT_DATA)-1) AS NUMERIC)/
								  (SELECT SUM(NUMBER_OF_CASUALTIES)
								  FROM ROAD_ACCIDENT_DATA
								  WHERE ACCIDENT_SEVERITY = 'Serious' AND YEAR = (SELECT MAX(YEAR) FROM ROAD_ACCIDENT_DATA)-1))*100, 2) || ' %' AS CY_VS_PY_PCT
FROM ROAD_ACCIDENT_DATA
WHERE YEAR = (SELECT MAX(YEAR) FROM ROAD_ACCIDENT_DATA) AND ACCIDENT_SEVERITY = 'Serious') AS Y;

-- find current year total number of casualties for fatal and compare increase or decrease percentage CY vs PY
SELECT TOTAL_SLIGHT_CASUALTIES, CY_VS_PY_PCT
FROM (SELECT ROUND(CAST(SUM(NUMBER_OF_CASUALTIES) AS NUMERIC)/1000, 2) || ' K' AS TOTAL_SLIGHT_CASUALTIES
FROM ROAD_ACCIDENT_DATA
WHERE YEAR = (SELECT MAX(YEAR) FROM ROAD_ACCIDENT_DATA) AND ACCIDENT_SEVERITY = 'Slight') AS X
CROSS JOIN (SELECT ROUND((CAST(SUM(NUMBER_OF_CASUALTIES)-(SELECT SUM(NUMBER_OF_CASUALTIES)
								  FROM ROAD_ACCIDENT_DATA
								  WHERE ACCIDENT_SEVERITY = 'Slight' AND YEAR = (SELECT MAX(YEAR) FROM ROAD_ACCIDENT_DATA)-1) AS NUMERIC)/
								  (SELECT SUM(NUMBER_OF_CASUALTIES)
								  FROM ROAD_ACCIDENT_DATA
								  WHERE ACCIDENT_SEVERITY = 'Slight' AND YEAR = (SELECT MAX(YEAR) FROM ROAD_ACCIDENT_DATA)-1))*100, 2) || ' %' AS CY_VS_PY_PCT
FROM ROAD_ACCIDENT_DATA
WHERE YEAR = (SELECT MAX(YEAR) FROM ROAD_ACCIDENT_DATA) AND ACCIDENT_SEVERITY = 'Slight') AS Y;

-- find casualties by vehicle type
SELECT VEHICLE_TYPE, SUM(TOTAL_CASUALTIES) AS TOTAL_CASUALTIES
FROM (SELECT CASE
			WHEN VEHICLE_TYPE IN ('Motorcycle 125cc and under', 'Motorcycle 50cc and under', 'Motorcycle over 125cc and up to 500cc',
								 'Motorcycle over 500cc', 'Pedal cycle') THEN 'Bike'
			WHEN VEHICLE_TYPE IN ('Bus or coach (17 or more pass seats)', 'Minibus (8 - 16 passenger seats)') THEN 'Bus'
			WHEN VEHICLE_TYPE IN ('Car', 'Taxi/Private hire car') THEN 'Car'
			WHEN VEHICLE_TYPE IN ('Goods 7.5 tonnes mgw and over', 'Goods over 3.5t. and under 7.5t', 'Van / Goods 3.5 tonnes mgw or under') THEN 'Van'
			WHEN VEHICLE_TYPE = 'Agricultural vehicle' THEN 'Agricultural'
			WHEN VEHICLE_TYPE IN ('Other vehicle', 'Ridden horse') THEN 'Other'
			END AS VEHICLE_TYPE,
		SUM(NUMBER_OF_CASUALTIES) AS TOTAL_CASUALTIES
		FROM ROAD_ACCIDENT_DATA
		WHERE YEAR = (SELECT MAX(YEAR) FROM ROAD_ACCIDENT_DATA)
		GROUP BY VEHICLE_TYPE) AS X
GROUP BY X.VEHICLE_TYPE
ORDER BY X.VEHICLE_TYPE

-- current year casualties vs previous year casualties monthly trend
SELECT YEAR, MONTH, 
ROUND(CAST(SUM(NUMBER_OF_CASUALTIES) AS NUMERIC)/1000, 2) || ' K' AS TOTAL_CASULATIES
FROM ROAD_ACCIDENT_DATA
GROUP BY YEAR, MONTH, MONTH_NUMBER
ORDER BY MONTH_NUMBER;

-- casualties by urban/rural
SELECT URBAN_OR_RURAL_AREA, 
ROUND((CAST(SUM(NUMBER_OF_CASUALTIES) AS NUMERIC)/(SELECT SUM(NUMBER_OF_CASUALTIES) FROM ROAD_ACCIDENT_DATA 
												   WHERE YEAR = (SELECT MAX(YEAR) FROM ROAD_ACCIDENT_DATA)))*100, 2)
												   || ' %' AS PCT
FROM ROAD_ACCIDENT_DATA
WHERE YEAR = (SELECT MAX(YEAR) FROM ROAD_ACCIDENT_DATA)
GROUP BY URBAN_OR_RURAL_AREA;

-- casualties by road type
SELECT ROAD_TYPE, ROUND((CAST(SUM(NUMBER_OF_CASUALTIES) AS NUMERIC)/1000)) || ' K' AS TOTAL_CASUALTIES
FROM ROAD_ACCIDENT_DATA
WHERE YEAR = (SELECT MAX(YEAR) FROM ROAD_ACCIDENT_DATA)
GROUP BY ROAD_TYPE;

-- casualties by light conditions
SELECT CASE
	WHEN LIGHT_CONDITIONS = 'Daylight' THEN 'Day'
	ELSE 'Light'
	END AS LIGHT_CONDITION,
ROUND((CAST(SUM(NUMBER_OF_CASUALTIES) AS NUMERIC)/(SELECT SUM(NUMBER_OF_CASUALTIES) FROM ROAD_ACCIDENT_DATA 
												   WHERE YEAR = (SELECT MAX(YEAR) FROM ROAD_ACCIDENT_DATA)))*100, 2)
												   || ' %' AS PCT
FROM ROAD_ACCIDENT_DATA
WHERE YEAR = (SELECT MAX(YEAR) FROM ROAD_ACCIDENT_DATA)
GROUP BY LIGHT_CONDITION;